In [3]:
from pathlib import Path
import pandas as pd

In [4]:
#reading in urban/suburban data
df = pd.read_csv(Path('../Resources/cal_rural_urban.csv'))
df

        county_name urban_rural
0           Alameda       urban
1            Alpine       rural
2            Amador       rural
3             Butte    suburban
4         Calaveras       rural
5            Colusa       rural
6      Contra Costa       urban
7         Del Norte       rural
8         El Dorado       rural
9            Fresno       urban
10            Glenn       rural
11         Humboldt       rural
12         Imperial    suburban
13             Inyo       rural
14             Kern    suburban
15            Kings       rural
16             Lake       rural
17           Lassen       rural
18      Los Angeles       urban
19           Madera       rural
20            Marin    suburban
21         Mariposa       rural
22        Mendocino       rural
23           Merced    suburban
24            Modoc       rural
25             Mono       rural
26         Monterey    suburban
27             Napa    suburban
28           Nevada       rural
29           Orange       urban
30           Placer    suburban
31           Plumas       rural
32        Riverside       urban
33       Sacramento       urban
34       San Benito       rural
35   San Bernardino       urban
36        San Diego       urban
37    San Francisco       urban
38      San Joaquin       urban
39  San Luis Obispo    suburban
40        San Mateo       urban
41    Santa Barbara    suburban
42      Santa Clara       urban
43       Santa Cruz    suburban
44           Shasta    suburban
45           Sierra       rural
46         Siskiyou       rural
47           Solano    suburban
48           Sonoma    suburban
49       Stanislaus    suburban
50           Sutter       rural
51           Tehama       rural
52          Trinity       rural
53           Tulare    suburban
54         Tuolumne       rural
55          Ventura       urban
56             Yolo    suburban
57             Yuba       rural

In [5]:
#renaming the columns
df.rename(columns={"county_name": "County", "urban_rural": "Description"}, inplace = True)

In [6]:
df

             County Description
0           Alameda       urban
1            Alpine       rural
2            Amador       rural
3             Butte    suburban
4         Calaveras       rural
5            Colusa       rural
6      Contra Costa       urban
7         Del Norte       rural
8         El Dorado       rural
9            Fresno       urban
10            Glenn       rural
11         Humboldt       rural
12         Imperial    suburban
13             Inyo       rural
14             Kern    suburban
15            Kings       rural
16             Lake       rural
17           Lassen       rural
18      Los Angeles       urban
19           Madera       rural
20            Marin    suburban
21         Mariposa       rural
22        Mendocino       rural
23           Merced    suburban
24            Modoc       rural
25             Mono       rural
26         Monterey    suburban
27             Napa    suburban
28           Nevada       rural
29           Orange       urban
30           Placer    suburban
31           Plumas       rural
32        Riverside       urban
33       Sacramento       urban
34       San Benito       rural
35   San Bernardino       urban
36        San Diego       urban
37    San Francisco       urban
38      San Joaquin       urban
39  San Luis Obispo    suburban
40        San Mateo       urban
41    Santa Barbara    suburban
42      Santa Clara       urban
43       Santa Cruz    suburban
44           Shasta    suburban
45           Sierra       rural
46         Siskiyou       rural
47           Solano    suburban
48           Sonoma    suburban
49       Stanislaus    suburban
50           Sutter       rural
51           Tehama       rural
52          Trinity       rural
53           Tulare    suburban
54         Tuolumne       rural
55          Ventura       urban
56             Yolo    suburban
57             Yuba       rural

In [7]:
#dataframe for county sizes
df_sizes = pd.read_csv(Path('../Resources/county_sizes.csv'))
df_sizes

    Unnamed: 0           County  County_Size(SqMile)
0            0          Alameda                  739
1            1           Alpine                  738
2            2           Amador                  595
3            3            Butte                 1636
4            4        Calaveras                 1020
5            5           Colusa                 1151
6            6     Contra Costa                  716
7            7        Del Norte                 1006
8            8        El Dorado                 1708
9            9           Fresno                 5958
10          10            Glenn                 1314
11          11         Humboldt                 3568
12          12         Imperial                 4177
13          13             Inyo                10181
14          14             Kern                 8132
15          15            Kings                 1389
16          16             Lake                 1256
17          17           Lassen                 4541
18          18      Los Angeles                 4058
19          19           Madera                 2137
20          20            Marin                  520
21          21         Mariposa                 1449
22          22        Mendocino                 3506
23          23           Merced                 1935
24          24            Modoc                 3918
25          25             Mono                 3049
26          26         Monterey                 3381
27          27             Napa                  748
28          28           Nevada                  958
29          29           Orange                  791
30          30           Placer                 1407
31          31           Plumas                 2553
32          32        Riverside                 7206
33          33       Sacramento                  965
34          34       San Benito                 1389
35          35   San Bernardino                20057
36          36        San Diego                 4207
37          37    San Francisco                   47
38          38      San Joaquin                 1391
39          39  San Luis Obispo                 3299
40          40        San Mateo                  448
41          41    Santa Barbara                 2735
42          42      Santa Clara                 1290
43          43       Santa Cruz                  445
44          44           Shasta                 3775
45          45           Sierra                  953
46          46         Siskiyou                 6278
47          47           Solano                  822
48          48           Sonoma                 1576
49          49       Stanislaus                 1495
50          50           Sutter                  602
51          51           Tehama                 2950
52          52          Trinity                 3179
53          53           Tulare                 4824
54          54         Tuolumne                 2221
55          55          Ventura                 1843
56          56             Yolo                 1015
57          57             Yuba                  632

In [8]:
#deleting the index column
df_sizes.drop(columns=['Unnamed: 0'], inplace= True)

In [9]:
df_sizes

             County  County_Size(SqMile)
0           Alameda                  739
1            Alpine                  738
2            Amador                  595
3             Butte                 1636
4         Calaveras                 1020
5            Colusa                 1151
6      Contra Costa                  716
7         Del Norte                 1006
8         El Dorado                 1708
9            Fresno                 5958
10            Glenn                 1314
11         Humboldt                 3568
12         Imperial                 4177
13             Inyo                10181
14             Kern                 8132
15            Kings                 1389
16             Lake                 1256
17           Lassen                 4541
18      Los Angeles                 4058
19           Madera                 2137
20            Marin                  520
21         Mariposa                 1449
22        Mendocino                 3506
23           Merced                 1935
24            Modoc                 3918
25             Mono                 3049
26         Monterey                 3381
27             Napa                  748
28           Nevada                  958
29           Orange                  791
30           Placer                 1407
31           Plumas                 2553
32        Riverside                 7206
33       Sacramento                  965
34       San Benito                 1389
35   San Bernardino                20057
36        San Diego                 4207
37    San Francisco                   47
38      San Joaquin                 1391
39  San Luis Obispo                 3299
40        San Mateo                  448
41    Santa Barbara                 2735
42      Santa Clara                 1290
43       Santa Cruz                  445
44           Shasta                 3775
45           Sierra                  953
46         Siskiyou                 6278
47           Solano                  822
48           Sonoma                 1576
49       Stanislaus                 1495
50           Sutter                  602
51           Tehama                 2950
52          Trinity                 3179
53           Tulare                 4824
54         Tuolumne                 2221
55          Ventura                 1843
56             Yolo                 1015
57             Yuba                  632

In [10]:
#merging the county sizes and description by county name 
cal_county_info = pd.merge(df, df_sizes, how="left", on="County")

In [11]:
cal_county_info.to_csv(Path('../Clean_datasets/Cal_county_geo.csv'), index = False, header = True)

In [12]:
cal_county_info

             County Description  County_Size(SqMile)
0           Alameda       urban                  739
1            Alpine       rural                  738
2            Amador       rural                  595
3             Butte    suburban                 1636
4         Calaveras       rural                 1020
5            Colusa       rural                 1151
6      Contra Costa       urban                  716
7         Del Norte       rural                 1006
8         El Dorado       rural                 1708
9            Fresno       urban                 5958
10            Glenn       rural                 1314
11         Humboldt       rural                 3568
12         Imperial    suburban                 4177
13             Inyo       rural                10181
14             Kern    suburban                 8132
15            Kings       rural                 1389
16             Lake       rural                 1256
17           Lassen       rural                 4541
18      Los Angeles       urban                 4058
19           Madera       rural                 2137
20            Marin    suburban                  520
21         Mariposa       rural                 1449
22        Mendocino       rural                 3506
23           Merced    suburban                 1935
24            Modoc       rural                 3918
25             Mono       rural                 3049
26         Monterey    suburban                 3381
27             Napa    suburban                  748
28           Nevada       rural                  958
29           Orange       urban                  791
30           Placer    suburban                 1407
31           Plumas       rural                 2553
32        Riverside       urban                 7206
33       Sacramento       urban                  965
34       San Benito       rural                 1389
35   San Bernardino       urban                20057
36        San Diego       urban                 4207
37    San Francisco       urban                   47
38      San Joaquin       urban                 1391
39  San Luis Obispo    suburban                 3299
40        San Mateo       urban                  448
41    Santa Barbara    suburban                 2735
42      Santa Clara       urban                 1290
43       Santa Cruz    suburban                  445
44           Shasta    suburban                 3775
45           Sierra       rural                  953
46         Siskiyou       rural                 6278
47           Solano    suburban                  822
48           Sonoma    suburban                 1576
49       Stanislaus    suburban                 1495
50           Sutter       rural                  602
51           Tehama       rural                 2950
52          Trinity       rural                 3179
53           Tulare    suburban                 4824
54         Tuolumne       rural                 2221
55          Ventura       urban                 1843
56             Yolo    suburban                 1015
57             Yuba       rural                  632

## population data cleaning

In [22]:
#creating the population dataframe
df_population = pd.read_csv(Path('../Resources/Cal_county_pop.csv'))
df_population.head(5)

,County,2010,2011,2012,2013,2014,2015,2016,2017,2018,...,Pop%_2010,Pop%_2011,Pop%_2012,Pop%_2013,Pop%_2014,Pop%_2015,Pop%_2016,Pop%_2017,Pop%_2018,Pop%_2019
0,Alameda,1512986.0,1530915.0,1553764.0,1579593.0,1607792.0,1634538.0,1650950.0,1660196.0,1666756.0,...,4.054143,4.067432,4.094369,4.128491,4.165591,4.199949,4.215143,4.218139,4.223743,4.229904
1,Alpine,1161.0,1093.0,1110.0,1128.0,1080.0,1077.0,1047.0,1111.0,1089.0,...,0.003111,0.002904,0.002925,0.002948,0.002798,0.002767,0.002673,0.002823,0.002760,0.002857
2,Amador,37886.0,37543.0,37104.0,36620.0,36726.0,37031.0,37429.0,38529.0,39405.0,...,0.101518,0.099747,0.097774,0.095712,0.095153,0.095151,0.095562,0.097892,0.099857,0.100607
3,Butte,219949.0,219975.0,220869.0,221641.0,223516.0,224631.0,226231.0,228696.0,230339.0,...,0.589367,0.584443,0.582018,0.579290,0.579102,0.577190,0.577604,0.581059,0.583704,0.554730
4,Calaveras,45468.0,45160.0,44815.0,44655.0,44671.0,44965.0,45322.0,45681.0,45698.0,...,0.121834,0.119984,0.118093,0.116712,0.115737,0.115538,0.115714,0.116064,0.115804,0.116179

In [23]:
#deleting years outside of the analysis scope
df_population.drop(columns=['2010','2011','2012','2013','Pop%_2010','Pop%_2011','Pop%_2012','Pop%_2013'], inplace= True)

In [24]:
df_population.head(5)

,County,2014,2015,2016,2017,2018,2019,Pop%_2014,Pop%_2015,Pop%_2016,Pop%_2017,Pop%_2018,Pop%_2019
0,Alameda,1607792.0,1634538.0,1650950.0,1660196.0,1666756.0,1671329.0,4.165591,4.199949,4.215143,4.218139,4.223743,4.229904
1,Alpine,1080.0,1077.0,1047.0,1111.0,1089.0,1129.0,0.002798,0.002767,0.002673,0.002823,0.002760,0.002857
2,Amador,36726.0,37031.0,37429.0,38529.0,39405.0,39752.0,0.095153,0.095151,0.095562,0.097892,0.099857,0.100607
3,Butte,223516.0,224631.0,226231.0,228696.0,230339.0,219186.0,0.579102,0.577190,0.577604,0.581059,0.583704,0.554730
4,Calaveras,44671.0,44965.0,45322.0,45681.0,45698.0,45905.0,0.115737,0.115538,0.115714,0.116064,0.115804,0.116179

In [25]:
df_population.to_csv(Path('../Clean_datasets/Cal_county_population.csv'), index = False, header = True)

In [26]:
df_population.dtypes

County        object
2014         float64
2015         float64
2016         float64
2017         float64
2018         float64
2019         float64
Pop%_2014    float64
Pop%_2015    float64
Pop%_2016    float64
Pop%_2017    float64
Pop%_2018    float64
Pop%_2019    float64
dtype: object